/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeu_jungle;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author albou
 */
public class IHMMessageVictoire extends javax.swing.JFrame {

    private File fichierfond2 = new File("src/Image/fond2.png");
    private File fichierCoupe = new File("src/Image/coupe.png");
    
    private BufferedImage imagefond2;
    private BufferedImage imageCoupe;
    
    public IHMMessageVictoire() {
        initComponents();
        setTitle("Message de Victoire");
        
        setBounds(650,250,500,400);
        jPanelFond2.setFocusable(true);
        try {
            imagefond2 = ImageIO.read(fichierfond2);
            imageCoupe = ImageIO.read(fichierCoupe);
            
        } catch(IOException ex) {
            System.out.println("fichier introuvable");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFond2 = new javax.swing.JPanel(){
            public void paintComponent (Graphics g){
                g.drawImage(imagefond2,0,0,500,400,null);
                g.drawImage(imageCoupe,0,0,60,40,null);
            }}
            ;
            jLabelGagne = new javax.swing.JLabel();
            jLabelRejoue = new javax.swing.JLabel();
            jButtonOui = new javax.swing.JButton();
            jButton1 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabelGagne.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            jLabelGagne.setText("BRAVO VOUS AVEZ GAGNÉ !!!!");

            jLabelRejoue.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabelRejoue.setText("Voulez vous rejouer et montrer qui est le roi de la jungle ? ");

            jButtonOui.setBackground(new java.awt.Color(131, 198, 131));
            jButtonOui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButtonOui.setForeground(new java.awt.Color(0, 102, 51));
            jButtonOui.setText("Oui");

            jButton1.setBackground(new java.awt.Color(131, 198, 131));
            jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton1.setForeground(new java.awt.Color(0, 102, 51));
            jButton1.setText("Non");

            javax.swing.GroupLayout jPanelFond2Layout = new javax.swing.GroupLayout(jPanelFond2);
            jPanelFond2.setLayout(jPanelFond2Layout);
            jPanelFond2Layout.setHorizontalGroup(
                jPanelFond2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFond2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelRejoue, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelFond2Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jButtonOui)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(105, 105, 105))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFond2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGagne)
                    .addGap(77, 77, 77))
            );
            jPanelFond2Layout.setVerticalGroup(
                jPanelFond2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFond2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabelGagne)
                    .addGap(139, 139, 139)
                    .addComponent(jLabelRejoue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addGroup(jPanelFond2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOui)
                        .addComponent(jButton1))
                    .addContainerGap(88, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelFond2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelFond2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMMessageVictoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMMessageVictoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMMessageVictoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMMessageVictoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMMessageVictoire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOui;
    private javax.swing.JLabel jLabelGagne;
    private javax.swing.JLabel jLabelRejoue;
    private javax.swing.JPanel jPanelFond2;
    // End of variables declaration//GEN-END:variables
}
